### ISSUE TITLE
The output pharmacophore is not saved as json pharmit file

### ISSUE THREAD

**Issue by MuhammadIIsmail** [sfernando-BAEN/ELIXIR-A#2]
After submitting ELIXIR-A job, the output refined pharmacophore is not saved as json pharmit-compatible file that can be used for screening by pharmit. I used version 2.1.

**Comment by Curiouss** [comment]
If the output is printed in the terminal, you can screen your molecule with the printed pharmacophore information by pharmit. If an error message appears, please check the python environment.

**Comment by MuhammadIIsmail** [comment]
There is no error appears. The refined pharmacophore appears.
![image](https://user-images.githubusercontent.com/19835485/199002812-7f98c356-ffb9-4209-a18a-816f335844c8.png)

But there is no output in the terminal that can be used in pharmit search, as I see.
![image](https://user-images.githubusercontent.com/19835485/199002975-70289893-a102-4952-82b9-831503842f47.png)

I think this was in older versions.

**Comment by Curiouss** [comment]
Hi Muhammad,

Yes, we didn't include the feature of JSON output in version V2.1. I have uploaded the new version v2.1.1 in [release](https://github.com/sfernando-BAEN/ELIXIR-A/releases), recovering the JSON output. Please let me know if you have any questions about it.

Best,
Haoqi

**Comment by MuhammadIIsmail** [comment]
Hello Haoqi,

It now works very well. Thank you so much.

Best regards,
Muhammad
