### ISSUE TITLE
Unable to add the plug-in to VMD

### ISSUE THREAD

**Issue by Moalaa17V** [sfernando-BAEN/ELIXIR-A#3]
Hello there, 

I downloaded the required dependencies.

![image](https://github.com/sfernando-BAEN/ELIXIR-A/assets/124233979/16600925-b454-4bb5-9970-0e024749e4be)

![image](https://github.com/sfernando-BAEN/ELIXIR-A/assets/124233979/15513b07-7626-4b07-9be3-e4fc6115335b)

I downloaded Elixir A Version 2.1.1, and I downloaded elixir2.0 folder then proceeded to add it to the TCL plugins directory /plugins/noarch/tcl, 

and in the scripts/vmd/loadplugins.tcl I added the line  vmd_install_extension elixir elixir_tk "Modeling/ELIXIR-A" under the ### Modelling menu

![image](https://github.com/sfernando-BAEN/ELIXIR-A/assets/124233979/83c3ec01-3e50-4111-9f88-78f44a7c9284)

When I open vmd and check the extensions menu the plug in is no where to be found, what am I doing wrong? Thank you!

**Comment by sfernando-BAEN** [comment]
Haoqi,

Could you please respond?

Thanks, Dr. Fernando

San Fernando, Ph.D., P.E.
Professor and Associate Department Head for Graduate Programs and Research
Biological and Agricultural Engineering Department
Texas A&M University

On Jul 15, 2023, at 1:45 PM, Moalaa17V ***@***.***> wrote:

﻿
Hello there, I downloaded the required dependencies. I downloaded Elixir A Version 2. 1. 1, and I downloaded elixir2. 0 folder then proceeded to add it to the TCL plugins directory /plugins/noarch/tcl, and in the scripts/vmd/loadplugins. tcl I
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.

ZjQcmQRYFpfptBannerEnd

Hello there,

I downloaded the required dependencies.

[image]<https://urldefense.com/v3/__https://user-images.githubusercontent.com/124233979/253763501-16600925-b454-4bb5-9970-0e024749e4be.png__;!!KwNVnqRv!G83J7mbVunr5c2AcoRdKXx8kFwUyoer9DLTWaEmNvLu_6xkwvwr12cf7hlGoG6M7SEbbc1V2eHWdkvUrDkdfUl05bg$>

[image]<https://urldefense.com/v3/__https://user-images.githubusercontent.com/124233979/253763482-15513b07-7626-4b07-9be3-e4fc6115335b.png__;!!KwNVnqRv!G83J7mbVunr5c2AcoRdKXx8kFwUyoer9DLTWaEmNvLu_6xkwvwr12cf7hlGoG6M7SEbbc1V2eHWdkvUrDkd1LXi14Q$>

I downloaded Elixir A Version 2.1.1, and I downloaded elixir2.0 folder then proceeded to add it to the TCL plugins directory /plugins/noarch/tcl, and in the scripts/vmd/loadplugins.tcl I added the line vmd_install_extension elixir elixir_tk "Modeling/ELIXIR-A" under the ### Modelling menu

When I open vmd and check the extensions menu the plug in is no where to be found, what am I doing wrong? Thank you!

**Comment by Curiouss** [comment]
Hi,

I just tested the latest VMD v1.9.4 and ELIXIR v2.1.1 on my system. I need some more information for resolving your problem.

If you can check the folder name of ELIXIR is `elixir2.1.1` which you placed in  `/plugins/noarch/tcl/`. And please check if the folder name matches the information in the file `/plugins/noarch/tcl/elixir2.1.1/pkgIndex.tcl`. You don't need to download the v2.0 folder at this moment. The `elixir2.1.1` folder can be downloaded [here](https://github.com/sfernando-BAEN/ELIXIR-A/releases/tag/v2.1.1).

If the package is not available, you may find some error message in the terminal of VMD. Loading the GUI should not rely on any conda / python environment. 

Best,
Haoqi

**Comment by Moalaa17V** [comment]
Hello Haoqi, 

Thank you for your prompt response. 

I uninstalled vmd and started over using the link to version 2.1.1 that you provided. In the previous attempt, I was working with version 2.0.

I added the folder to plugins/noarch/tcl:
![image](https://github.com/sfernando-BAEN/ELIXIR-A/assets/124233979/65004960-7e6a-4b53-8eb2-d9a86a572ac4)

I made sure that the information pkgIndex.tcl matches the folder name. The original file had the following line:

package ifneeded elixir 2.11 "set env(ELIXIRDIR) [list $dir] ; [list source [file join $dir ELIXIR-A.tcl]]"

I left it as is and tried running again, the Elixir-A plugin did not load still.

I tried editing the line to exactly match the folder name as in this example:

![image](https://github.com/sfernando-BAEN/ELIXIR-A/assets/124233979/db16a875-17e8-4317-ae38-35487a787001)

The issue still persisted. 

I am not running vmd using any Python environment.

![image](https://github.com/sfernando-BAEN/ELIXIR-A/assets/124233979/29229d03-a68d-496a-bff6-86e404e780bc)


Please let me know if there's anything else I could do to fix this issue. 

Appreciate your help!

Thank you.

**Comment by Curiouss** [comment]
Hello,

I didn't see anything abnormal here. Based on the image you showed here. You may forget to `add vmd_install_extension elixir elixir_tk  "Modeling/ELIXIR-A"` in the $VMDPATH/scripts/vmd/loadplugin.tcl file.

You can check `which vmd` command to see if you placed the files in the correct vmd folder which you called vmd for GUI.

**Comment by Moalaa17V** [comment]
Hello, Haoqi 
It worked!
It seems that I needed to apply the edits to the script in the vmd directory in /usr//local/lib 
Thank you so much!
